### ISSUE TITLE
metaHandler.js UC浏览器的问题

### ISSUE THREAD

**Issue by heby** [unbug/generator-webappstarter#2]
UC浏览器中会将页面缩放，代码如下

```
<meta content="target-densitydpi=device-dpi,width=720" name="viewport">
<style type="text/css">
body{width: 720px;}
</style>
<script> (new MetaHandler()).fixViewportWidth(); </script>
```

UC的效果：
![image](https://cloud.githubusercontent.com/assets/3339694/8202638/70832262-150e-11e5-95a5-58b645d72958.png)
Chrome、QQ浏览器的效果：
![image](https://cloud.githubusercontent.com/assets/3339694/8202649/8740f1f0-150e-11e5-9506-6e2fd95f08b7.png)
但是我用UC打开你们的demo站【 http://c.3g.163.com/CreditMarket/default.html 】 时，却不会这样，求解答。

**Comment by unbug** [comment]
我的DEMO只是示范body的宽度和viewport的相同。你的页面应该有其他基本的CSS样式的，比如

``` css
html{width: 100%;}
```

或者你可以用本[generator-webappstarter](https://github.com/unbug/generator-webappstarter) 生成一个网站来测试，里面有一些基础的CSS样式。
