### ISSUE TITLE
请教MetaHandler.js的问题

### ISSUE THREAD

**Issue by MichaelGong** [unbug/generator-webappstarter#3]
请问你们在实际项目中时候遇到使用了MetaHandler.js，宽度按照640px来完成的，但是到手机上展示的时候，页面的宽度超过了手机的宽度，造成一部分内容无法显示，请问中问题是否遇到？遇到了怎么解决的？谢谢~~

**Comment by unbug** [comment]
MetaHandler.js本身就是用来解决页面宽度超过了手机宽度的。
你的body要是640,内容宽度在body里不能超过640。
对于没有时间看注释里原理PPT连接的同学，你们可以使用本generator-webappstarter生成一个范例参考。

**Comment by MichaelGong** [comment]
可能是我表述的不清楚，我的body是640，而且内容也没有超过640px，我出现的问题是有某些机型会不能正常展示页面（目前测试的机型大部分都能正常展示），也就是说 动态设置viewport无法正常起作用，一直没有找到其中的原因，不知道你们有没有遇到过？

**Comment by unbug** [comment]
Note:
     \*  For iOS it just works perfectly,if it's not,try to use "webView.scalesPageToFit = YES" in the webview.
     \*  For android it works in all of build-in broswers,it might be break in some third-part ROM's build-in broswers(webview).
     \*  That's because they don't do a good job for the webview,such as they should not use "webview.setBuiltInZoomControls(false)".
     *
