### ISSUE TITLE
不知道你们对The key "target-densitydpi" is not supported.you什么看法

### ISSUE THREAD

**Issue by seekwe** [unbug/generator-webappstarter#5]
去年我也是用这种方案,但是整天看到这句话The key "target-densitydpi" is not supported.最后还是抛弃了

**Comment by unbug** [comment]
但是你看到这个警告也不影响页面渲染。`target-densitydpi` 是对android 3.x-以下机型的适配, （特别是三星和国产等 webview 不严谨的机型）,
如果不考虑，你可以修改[`html/include/htmlhead.html`]文件，去掉`target-densitydpi=device-dpi`

```
<meta content="width=_VIEWPORT_WIDTH_" name="viewport">
```

如果其他文件还有同样去掉即可 :)
